# Generated by Django 5.0.6 on 2024-05-29 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_app', '0002_messages_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='cars_app.car'),
        ),
    ]
