# Generated by Django 5.0.6 on 2024-05-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_app', '0002_remove_car_cart_remove_cart_quantity_car_carts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='carts',
            field=models.ManyToManyField(blank=True, related_name='cars', to='cars_app.cart'),
        ),
    ]
