# Generated by Django 2.2.4 on 2024-05-26 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars_app', '0002_auto_20240526_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars_app.Cart'),
        ),
        migrations.AlterField(
            model_name='car',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='cars', to='cars_app.User'),
        ),
    ]
